abstract final class AppRoutes {
  static const splash = 'splash';
  static const welcome = 'welcome';
  static const login = 'login';
  static const registerCompany = 'registerCompany';
  static const joinRequest = 'joinRequest';
  static const acceptInvitation = 'acceptInvitation';
  static const pending = 'pending';
  static const home = 'home';
  static const invitations = 'invitations';
  static const joinRequestsAdmin = 'joinRequestsAdmin';
  static const projects = 'projects';
  static const projectCreate = 'projectCreate';
  static const projectDetails = 'projectDetails';
  static const projectEdit = 'projectEdit';
  static const projectSupervisor = 'projectSupervisor';
  static const projectMembers = 'projectMembers';
  static const companyMembers = 'companyMembers';
  static const companyMemberDetails = 'companyMemberDetails';
  static const account = 'account';
  static const unavailable = 'unavailable';

  static const splashPath = '/';
  static const welcomePath = '/welcome';
  static const loginPath = '/login';
  static const registerCompanyPath = '/register-company';
  static const joinRequestPath = '/join-request';
  static const acceptInvitationPath = '/accept-invitation';
  static const pendingPath = '/pending';
  static const homePath = '/home';
  static const invitationsPath = '/access/invitations';
  static const joinRequestsPath = '/access/join-requests';
  static const projectsPath = '/projects';
  static const projectCreatePath = '/projects/new';
  static const companyMembersPath = '/company/members';
  static const accountPath = '/account';
  static const unavailablePath = '/unavailable';
}
