\set ON_ERROR_STOP on
-- PREPARATION ARTIFACT ONLY. NOT EXECUTED. Run only through the reviewed installation transaction.
\if :{?settlement_ddl_approved}
\else
\echo 'STOP: future execution requires separate approval and settlement_ddl_approved variable.'
\quit 3
\endif
\if :settlement_ddl_approved
\else
\echo 'STOP: settlement_ddl_approved must be true'
\quit 3
\endif

-- T06
CREATE TABLE ahdah.project_settlements (
    project_settlement_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    project_id uuid NOT NULL,
    cycle_number integer NOT NULL,
    previous_settlement_id uuid,
    status varchar(40) NOT NULL,
    operational_basis varchar(40) NOT NULL,
    captured_project_version integer NOT NULL,
    captured_financial_revision bigint NOT NULL,
    policy_version_id uuid NOT NULL,
    evaluator_version varchar(80) NOT NULL,
    snapshot_schema_version integer NOT NULL,
    evaluated_at timestamptz,
    prepared_by_user_id uuid NOT NULL,
    submitted_by_user_id uuid,
    approved_by_user_id uuid,
    submitted_at timestamptz,
    approved_at timestamptz,
    snapshot_id uuid,
    snapshot_hash bytea,
    notes varchar(1000),
    version_number integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t06 PRIMARY KEY (project_settlement_id),
    CONSTRAINT uq_t06_tenant UNIQUE (company_id, project_settlement_id),
    CONSTRAINT uq_t06_project UNIQUE (company_id, project_id, project_settlement_id),
    CONSTRAINT uq_t06_cycle UNIQUE (company_id, project_id, cycle_number),
    CONSTRAINT ck_t06_status CHECK (status IN ('Draft','Submitted','Approved','Rejected','Withdrawn','Superseded')),
    CONSTRAINT ck_t06_operational_basis CHECK (operational_basis IN ('Completed','Cancelled')),
    CONSTRAINT ck_t06_submission CHECK (status NOT IN ('Submitted','Approved') OR (submitted_by_user_id IS NOT NULL AND snapshot_id IS NOT NULL AND snapshot_hash IS NOT NULL AND evaluated_at IS NOT NULL)),
    CONSTRAINT ck_t06_approval CHECK (status <> 'Approved' OR (approved_by_user_id IS NOT NULL AND approved_by_user_id <> prepared_by_user_id AND approved_by_user_id <> submitted_by_user_id)),
    CONSTRAINT ck_t06_cycle_number_range CHECK (cycle_number>=1),
    CONSTRAINT ck_t06_status_text CHECK (status IS NULL OR btrim(status)<>''),
    CONSTRAINT ck_t06_operational_basis_text CHECK (operational_basis IS NULL OR btrim(operational_basis)<>''),
    CONSTRAINT ck_t06_captured_project_version_range CHECK (captured_project_version>=1),
    CONSTRAINT ck_t06_captured_financial_revision_range CHECK (captured_financial_revision>=1),
    CONSTRAINT ck_t06_evaluator_version_text CHECK (evaluator_version IS NULL OR btrim(evaluator_version)<>''),
    CONSTRAINT ck_t06_snapshot_schema_version_range CHECK (snapshot_schema_version>=1),
    CONSTRAINT ck_t06_snapshot_hash_hash CHECK (octet_length(snapshot_hash)=32),
    CONSTRAINT ck_t06_notes_text CHECK (notes IS NULL OR btrim(notes)<>''),
    CONSTRAINT ck_t06_version_number_range CHECK (version_number>=1),
    CONSTRAINT ck_t06_approved_by_user_id_pair CHECK ((approved_by_user_id IS NULL)=(approved_at IS NULL)),
    CONSTRAINT ck_t06_approved_at_order CHECK (approved_at IS NULL OR approved_at>=created_at),
    CONSTRAINT ck_t06_submitted_by_user_id_pair CHECK ((submitted_by_user_id IS NULL)=(submitted_at IS NULL)),
    CONSTRAINT ck_t06_submitted_at_order CHECK (submitted_at IS NULL OR submitted_at>=created_at)
);

-- T07
CREATE TABLE ahdah.project_settlement_snapshots (
    project_settlement_snapshot_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    project_id uuid NOT NULL,
    project_settlement_id uuid NOT NULL,
    snapshot_number integer NOT NULL,
    purpose varchar(40) NOT NULL,
    project_version integer NOT NULL,
    financial_revision bigint NOT NULL,
    policy_version_id uuid NOT NULL,
    evaluator_version varchar(80) NOT NULL,
    schema_version integer NOT NULL,
    evaluated_at timestamptz NOT NULL,
    canonical_payload bytea NOT NULL,
    payload jsonb NOT NULL,
    hash_algorithm varchar(80) NOT NULL,
    snapshot_hash bytea NOT NULL,
    evaluated_by_user_id uuid NOT NULL,
    blocker_count integer NOT NULL,
    mandatory_gap_count integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t07 PRIMARY KEY (project_settlement_snapshot_id),
    CONSTRAINT uq_t07_tenant UNIQUE (company_id, project_settlement_snapshot_id),
    CONSTRAINT uq_t07_project UNIQUE (company_id, project_id, project_settlement_snapshot_id),
    CONSTRAINT uq_t07_number UNIQUE (company_id, project_settlement_id, snapshot_number),
    CONSTRAINT uq_t07_cycle_reference UNIQUE (company_id, project_id, project_settlement_id, project_settlement_snapshot_id),
    CONSTRAINT ck_t07_purpose CHECK (purpose IN ('Evaluation','Submission','ApprovalCheck','ClosureCheck')),
    CONSTRAINT ck_t07_algorithm CHECK (hash_algorithm = 'SHA256'),
    CONSTRAINT ck_t07_payload_bytes CHECK (octet_length(canonical_payload) > 0),
    CONSTRAINT ck_t07_snapshot_number_range CHECK (snapshot_number>=1),
    CONSTRAINT ck_t07_purpose_text CHECK (purpose IS NULL OR btrim(purpose)<>''),
    CONSTRAINT ck_t07_project_version_range CHECK (project_version>=1),
    CONSTRAINT ck_t07_financial_revision_range CHECK (financial_revision>=1),
    CONSTRAINT ck_t07_evaluator_version_text CHECK (evaluator_version IS NULL OR btrim(evaluator_version)<>''),
    CONSTRAINT ck_t07_schema_version_range CHECK (schema_version>=1),
    CONSTRAINT ck_t07_payload_json CHECK (jsonb_typeof(payload)='object'),
    CONSTRAINT ck_t07_hash_algorithm_text CHECK (hash_algorithm IS NULL OR btrim(hash_algorithm)<>''),
    CONSTRAINT ck_t07_snapshot_hash_hash CHECK (octet_length(snapshot_hash)=32),
    CONSTRAINT ck_t07_blocker_count_range CHECK (blocker_count>=0),
    CONSTRAINT ck_t07_mandatory_gap_count_range CHECK (mandatory_gap_count>=0)
);

-- T08
CREATE TABLE ahdah.project_settlement_snapshot_categories (
    project_settlement_snapshot_category_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    project_id uuid NOT NULL,
    snapshot_id uuid NOT NULL,
    category_code varchar(80) NOT NULL,
    evaluation_status varchar(40) NOT NULL,
    currency_code varchar(3),
    amount_meaning varchar(40) NOT NULL,
    exact_amount numeric(18,2),
    blocker_count integer NOT NULL,
    gap_count integer NOT NULL,
    details jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t08 PRIMARY KEY (project_settlement_snapshot_category_id),
    CONSTRAINT uq_t08_tenant UNIQUE (company_id, project_settlement_snapshot_category_id),
    CONSTRAINT uq_t08_project UNIQUE (company_id, project_id, project_settlement_snapshot_category_id),
    CONSTRAINT uq_t08_category_amount UNIQUE NULLS NOT DISTINCT (company_id, snapshot_id, category_code, currency_code, amount_meaning),
    CONSTRAINT ck_t08_evaluation_status CHECK (evaluation_status IN ('Evaluated','NotVisible','NotAttributable','Unknown')),
    CONSTRAINT ck_t08_amount_scope CHECK ((currency_code IS NOT NULL OR exact_amount IS NULL) AND (evaluation_status = 'Evaluated' OR exact_amount IS NULL)),
    CONSTRAINT ck_t08_category_code_text CHECK (category_code IS NULL OR btrim(category_code)<>''),
    CONSTRAINT ck_t08_evaluation_status_text CHECK (evaluation_status IS NULL OR btrim(evaluation_status)<>''),
    CONSTRAINT ck_t08_currency CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_t08_amount_meaning_text CHECK (amount_meaning IS NULL OR btrim(amount_meaning)<>''),
    CONSTRAINT ck_t08_blocker_count_range CHECK (blocker_count>=0),
    CONSTRAINT ck_t08_gap_count_range CHECK (gap_count>=0),
    CONSTRAINT ck_t08_details_json CHECK (jsonb_typeof(details)='array')
);

-- T09
CREATE TABLE ahdah.project_settlement_events (
    project_settlement_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    project_id uuid NOT NULL,
    settlement_id uuid NOT NULL,
    event_number integer NOT NULL,
    event_type varchar(40) NOT NULL,
    actor_user_id uuid NOT NULL,
    actor_role varchar(40) NOT NULL,
    occurred_at timestamptz NOT NULL,
    reason varchar(1000),
    authorization_decision_id uuid,
    snapshot_id uuid,
    financial_revision bigint NOT NULL,
    record_version_before integer NOT NULL,
    record_version_after integer NOT NULL,
    idempotency_record_id uuid NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t09 PRIMARY KEY (project_settlement_event_id),
    CONSTRAINT uq_t09_tenant UNIQUE (company_id, project_settlement_event_id),
    CONSTRAINT uq_t09_project UNIQUE (company_id, project_id, project_settlement_event_id),
    CONSTRAINT uq_t09_number UNIQUE (company_id, settlement_id, event_number),
    CONSTRAINT uq_t09_replay UNIQUE (company_id, idempotency_record_id, event_type, settlement_id),
    CONSTRAINT ck_t09_event_type CHECK (event_type IN ('Created','Evaluated','Submitted','Approved','Rejected','Withdrawn','Superseded','Invalidated','Closed','Reopened')),
    CONSTRAINT ck_t09_versions CHECK (record_version_after >= record_version_before),
    CONSTRAINT ck_t09_event_number_range CHECK (event_number>=1),
    CONSTRAINT ck_t09_event_type_text CHECK (event_type IS NULL OR btrim(event_type)<>''),
    CONSTRAINT ck_t09_actor_role_text CHECK (actor_role IS NULL OR btrim(actor_role)<>''),
    CONSTRAINT ck_t09_reason_text CHECK (reason IS NULL OR btrim(reason)<>''),
    CONSTRAINT ck_t09_financial_revision_range CHECK (financial_revision>=1),
    CONSTRAINT ck_t09_record_version_before_range CHECK (record_version_before>=0),
    CONSTRAINT ck_t09_record_version_after_range CHECK (record_version_after>=1),
    CONSTRAINT ck_t09_payload_json CHECK (jsonb_typeof(payload)='object')
);

-- T10
CREATE TABLE ahdah.project_closure_certificates (
    project_closure_certificate_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    project_id uuid NOT NULL,
    project_settlement_id uuid NOT NULL,
    approved_snapshot_id uuid NOT NULL,
    closure_snapshot_id uuid NOT NULL,
    financial_revision bigint NOT NULL,
    policy_version_id uuid NOT NULL,
    closure_basis varchar(40) NOT NULL,
    closed_by_user_id uuid NOT NULL,
    actor_role varchar(40) NOT NULL,
    closed_at timestamptz NOT NULL,
    reason varchar(1000) NOT NULL,
    pre_close_project_version integer NOT NULL,
    post_close_project_version integer NOT NULL,
    approved_snapshot_hash bytea NOT NULL,
    closure_snapshot_hash bytea NOT NULL,
    closure_version integer NOT NULL,
    authorization_decision_id uuid NOT NULL,
    idempotency_record_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t10 PRIMARY KEY (project_closure_certificate_id),
    CONSTRAINT uq_t10_tenant UNIQUE (company_id, project_closure_certificate_id),
    CONSTRAINT uq_t10_project UNIQUE (company_id, project_id, project_closure_certificate_id),
    CONSTRAINT uq_t10_version UNIQUE (company_id, project_id, closure_version),
    CONSTRAINT uq_t10_replay UNIQUE (company_id, idempotency_record_id),
    CONSTRAINT ck_t10_closure_basis CHECK (closure_basis IN ('Completed','Cancelled')),
    CONSTRAINT ck_t10_actor_role CHECK (actor_role IN ('Manager')),
    CONSTRAINT ck_t10_project_versions CHECK ((closure_basis='Completed' AND post_close_project_version=pre_close_project_version+1) OR (closure_basis='Cancelled' AND post_close_project_version=pre_close_project_version)),
    CONSTRAINT ck_t10_financial_revision_range CHECK (financial_revision>=1),
    CONSTRAINT ck_t10_closure_basis_text CHECK (closure_basis IS NULL OR btrim(closure_basis)<>''),
    CONSTRAINT ck_t10_actor_role_text CHECK (actor_role IS NULL OR btrim(actor_role)<>''),
    CONSTRAINT ck_t10_reason_text CHECK (reason IS NULL OR btrim(reason)<>''),
    CONSTRAINT ck_t10_pre_close_project_version_range CHECK (pre_close_project_version>=1),
    CONSTRAINT ck_t10_post_close_project_version_range CHECK (post_close_project_version>=1),
    CONSTRAINT ck_t10_approved_snapshot_hash_hash CHECK (octet_length(approved_snapshot_hash)=32),
    CONSTRAINT ck_t10_closure_snapshot_hash_hash CHECK (octet_length(closure_snapshot_hash)=32),
    CONSTRAINT ck_t10_closure_version_range CHECK (closure_version>=1)
);

-- T11
CREATE TABLE ahdah.project_reopenings (
    project_reopening_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    project_id uuid NOT NULL,
    previous_closure_id uuid NOT NULL,
    new_settlement_id uuid NOT NULL,
    actor_user_id uuid NOT NULL,
    actor_role varchar(40) NOT NULL,
    reason varchar(1000) NOT NULL,
    reopened_at timestamptz NOT NULL,
    prior_financial_state varchar(40) NOT NULL,
    resulting_financial_state varchar(40) NOT NULL,
    revision_before bigint NOT NULL,
    revision_after bigint NOT NULL,
    pre_project_version integer NOT NULL,
    post_project_version integer NOT NULL,
    authorization_decision_id uuid NOT NULL,
    audit_log_id uuid NOT NULL,
    idempotency_record_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t11 PRIMARY KEY (project_reopening_id),
    CONSTRAINT uq_t11_tenant UNIQUE (company_id, project_reopening_id),
    CONSTRAINT uq_t11_project UNIQUE (company_id, project_id, project_reopening_id),
    CONSTRAINT uq_t11_previous_closure_id UNIQUE (company_id, previous_closure_id),
    CONSTRAINT uq_t11_new_settlement_id UNIQUE (company_id, new_settlement_id),
    CONSTRAINT uq_t11_idempotency_record_id UNIQUE (company_id, idempotency_record_id),
    CONSTRAINT ck_t11_actor_role CHECK (actor_role IN ('Manager')),
    CONSTRAINT ck_t11_prior_financial_state CHECK (prior_financial_state IN ('FinanciallyClosed')),
    CONSTRAINT ck_t11_resulting_financial_state CHECK (resulting_financial_state IN ('InSettlement')),
    CONSTRAINT ck_t11_revision CHECK (revision_after=revision_before+1),
    CONSTRAINT ck_t11_actor_role_text CHECK (actor_role IS NULL OR btrim(actor_role)<>''),
    CONSTRAINT ck_t11_reason_text CHECK (reason IS NULL OR btrim(reason)<>''),
    CONSTRAINT ck_t11_prior_financial_state_text CHECK (prior_financial_state IS NULL OR btrim(prior_financial_state)<>''),
    CONSTRAINT ck_t11_resulting_financial_state_text CHECK (resulting_financial_state IS NULL OR btrim(resulting_financial_state)<>''),
    CONSTRAINT ck_t11_revision_before_range CHECK (revision_before>=1),
    CONSTRAINT ck_t11_revision_after_range CHECK (revision_after>=1),
    CONSTRAINT ck_t11_pre_project_version_range CHECK (pre_project_version>=1),
    CONSTRAINT ck_t11_post_project_version_range CHECK (post_project_version>=1)
);

-- T12
CREATE TABLE ahdah.project_authorization_decisions (
    project_authorization_decision_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    project_id uuid NOT NULL,
    action_code varchar(40) NOT NULL,
    actor_user_id uuid NOT NULL,
    actor_role varchar(40) NOT NULL,
    decided_at timestamptz NOT NULL,
    decision varchar(40) NOT NULL,
    policy_version_id uuid NOT NULL,
    preparer_user_id uuid,
    submitter_user_id uuid,
    beneficiary_user_id uuid,
    conflict_detected boolean NOT NULL,
    conflict_reason varchar(1000),
    evidence_id uuid,
    delegation_reference uuid,
    request_hash bytea NOT NULL,
    details jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t12 PRIMARY KEY (project_authorization_decision_id),
    CONSTRAINT uq_t12_tenant UNIQUE (company_id, project_authorization_decision_id),
    CONSTRAINT uq_t12_project UNIQUE (company_id, project_id, project_authorization_decision_id),
    CONSTRAINT ck_t12_action_code CHECK (action_code IN ('Prepare','Submit','Approve','Close','Reopen','Acknowledge','Complete','Designate','Release','Reallocate','CorrectCustody','Exception','ReconcileOwner')),
    CONSTRAINT ck_t12_decision CHECK (decision IN ('Allowed','Denied')),
    CONSTRAINT ck_t12_actor_role CHECK (actor_role IN ('Manager','Deputy','Accountant','Supervisor')),
    CONSTRAINT ck_t12_delegation_v1 CHECK (delegation_reference IS NULL),
    CONSTRAINT ck_t12_conflict CHECK (NOT conflict_detected OR (conflict_reason IS NOT NULL AND decision='Denied')),
    CONSTRAINT ck_t12_action_code_text CHECK (action_code IS NULL OR btrim(action_code)<>''),
    CONSTRAINT ck_t12_actor_role_text CHECK (actor_role IS NULL OR btrim(actor_role)<>''),
    CONSTRAINT ck_t12_decision_text CHECK (decision IS NULL OR btrim(decision)<>''),
    CONSTRAINT ck_t12_conflict_reason_text CHECK (conflict_reason IS NULL OR btrim(conflict_reason)<>''),
    CONSTRAINT ck_t12_request_hash_hash CHECK (octet_length(request_hash)=32),
    CONSTRAINT ck_t12_details_json CHECK (jsonb_typeof(details)='object')
);

-- T13
CREATE TABLE ahdah.project_operational_events (
    project_operational_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL,
    project_id uuid NOT NULL,
    event_type varchar(40) NOT NULL,
    actor_user_id uuid NOT NULL,
    actor_role varchar(40) NOT NULL,
    occurred_at timestamptz NOT NULL,
    reason varchar(1000) NOT NULL,
    project_version_before integer NOT NULL,
    project_version_after integer NOT NULL,
    evidence_id uuid,
    acknowledgment_event_id uuid,
    authorization_decision_id uuid NOT NULL,
    idempotency_record_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t13 PRIMARY KEY (project_operational_event_id),
    CONSTRAINT uq_t13_tenant UNIQUE (company_id, project_operational_event_id),
    CONSTRAINT uq_t13_project UNIQUE (company_id, project_id, project_operational_event_id),
    CONSTRAINT uq_t13_replay UNIQUE (company_id, idempotency_record_id, event_type),
    CONSTRAINT ck_t13_event_type CHECK (event_type IN ('PhysicalAcknowledged','CompletionApproved','CancellationApproved')),
    CONSTRAINT ck_t13_role CHECK ((event_type='PhysicalAcknowledged' AND actor_role='Supervisor') OR (event_type IN ('CompletionApproved','CancellationApproved') AND actor_role='Manager')),
    CONSTRAINT ck_t13_versions CHECK (project_version_after >= project_version_before),
    CONSTRAINT ck_t13_event_type_text CHECK (event_type IS NULL OR btrim(event_type)<>''),
    CONSTRAINT ck_t13_actor_role_text CHECK (actor_role IS NULL OR btrim(actor_role)<>''),
    CONSTRAINT ck_t13_reason_text CHECK (reason IS NULL OR btrim(reason)<>''),
    CONSTRAINT ck_t13_project_version_before_range CHECK (project_version_before>=1),
    CONSTRAINT ck_t13_project_version_after_range CHECK (project_version_after>=1)
);
