\set ON_ERROR_STOP on
\echo 'PRE-CUTOVER EMPTY-SCHEMA ROLLBACK ONLY. POST-CUTOVER ROLLBACK IS NOT DROP TABLE.'
\if :{?rollback_approved}
\else
\quit 3
\endif
\if :rollback_approved
\else
\echo 'STOP: rollback_approved must be true'
\quit 3
\endif
BEGIN;
SET LOCAL lock_timeout='5s';
DO $guard$
BEGIN
 IF current_database()<>'ahdah_db' THEN RAISE EXCEPTION 'Wrong database'; END IF;
END $guard$;
LOCK TABLE ahdah.company_settlement_policy_bindings, ahdah.custody_movement_entries, ahdah.custody_operations, ahdah.custody_reservations, ahdah.document_custody_events, ahdah.document_policy_exceptions, ahdah.financial_resolution_effects, ahdah.legacy_attribution_review_projects, ahdah.legacy_attribution_reviews, ahdah.project_authorization_decisions, ahdah.project_closure_certificates, ahdah.project_custody_positions, ahdah.project_financial_controls, ahdah.project_operational_events, ahdah.project_owner_reconciliation_positions, ahdah.project_owner_reconciliations, ahdah.project_owner_retention_items, ahdah.project_reopenings, ahdah.project_settlement_events, ahdah.project_settlement_snapshot_categories, ahdah.project_settlement_snapshots, ahdah.project_settlements, ahdah.settlement_policy_versions, ahdah.supplier_credit_intent_applications, ahdah.supplier_credit_intents, ahdah.verified_evidence_objects IN ACCESS EXCLUSIVE MODE;
LOCK TABLE ahdah.projects,ahdah.project_contract_changes,ahdah.owner_payment_refunds,ahdah.user_advance_balances,ahdah.advances IN ACCESS EXCLUSIVE MODE;
DO $empty$ BEGIN
 IF EXISTS(SELECT 1 FROM ahdah.project_financial_controls) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_financial_controls'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_custody_positions) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_custody_positions'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.custody_operations) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: custody_operations'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.custody_movement_entries) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: custody_movement_entries'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.custody_reservations) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: custody_reservations'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_settlements) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_settlements'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_settlement_snapshots) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_settlement_snapshots'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_settlement_snapshot_categories) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_settlement_snapshot_categories'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_settlement_events) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_settlement_events'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_closure_certificates) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_closure_certificates'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_reopenings) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_reopenings'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_authorization_decisions) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_authorization_decisions'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_operational_events) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_operational_events'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.settlement_policy_versions) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: settlement_policy_versions'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.company_settlement_policy_bindings) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: company_settlement_policy_bindings'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.document_custody_events) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: document_custody_events'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.document_policy_exceptions) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: document_policy_exceptions'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.verified_evidence_objects) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: verified_evidence_objects'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_owner_reconciliations) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_owner_reconciliations'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_owner_reconciliation_positions) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_owner_reconciliation_positions'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.project_owner_retention_items) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: project_owner_retention_items'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.financial_resolution_effects) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: financial_resolution_effects'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.supplier_credit_intents) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: supplier_credit_intents'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.supplier_credit_intent_applications) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: supplier_credit_intent_applications'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.legacy_attribution_reviews) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: legacy_attribution_reviews'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.legacy_attribution_review_projects) THEN RAISE EXCEPTION 'Rollback refuses ANY new data: legacy_attribution_review_projects'; END IF;
 IF EXISTS(SELECT 1 FROM ahdah.projects WHERE contract_currency_code IS NOT NULL) OR EXISTS(SELECT 1 FROM ahdah.project_contract_changes WHERE currency_code IS NOT NULL) OR EXISTS(SELECT 1 FROM ahdah.owner_payment_refunds WHERE currency_code IS NOT NULL) THEN RAISE EXCEPTION 'Reviewed currency data exists; refuse destructive rollback'; END IF;
 IF EXISTS(SELECT 1 FROM pg_trigger WHERE tgname IN ('trg_settlement_project_control','trg_settlement_balance_conservation','trg_settlement_advance_currency') AND tgenabled<>'D') THEN RAISE EXCEPTION 'Enforcement activated; rollback boundary crossed'; END IF;
END $empty$;
DROP TRIGGER trg_t01_updated_at ON ahdah.project_financial_controls;
DROP TRIGGER trg_t01_fixed_keys ON ahdah.project_financial_controls;
DROP TRIGGER trg_t02_updated_at ON ahdah.project_custody_positions;
DROP TRIGGER trg_t02_fixed_keys ON ahdah.project_custody_positions;
DROP TRIGGER trg_t03_custody_authority ON ahdah.custody_operations;
DROP TRIGGER trg_t04_custody_authority ON ahdah.custody_movement_entries;
DROP TRIGGER trg_t03_updated_at ON ahdah.custody_operations;
DROP TRIGGER trg_t03_fixed_keys ON ahdah.custody_operations;
DROP TRIGGER trg_t04_immutable ON ahdah.custody_movement_entries;
DROP TRIGGER trg_t05_updated_at ON ahdah.custody_reservations;
DROP TRIGGER trg_t05_fixed_keys ON ahdah.custody_reservations;
DROP TRIGGER trg_t06_updated_at ON ahdah.project_settlements;
DROP TRIGGER trg_t06_fixed_keys ON ahdah.project_settlements;
DROP TRIGGER trg_t07_immutable ON ahdah.project_settlement_snapshots;
DROP TRIGGER trg_t08_immutable ON ahdah.project_settlement_snapshot_categories;
DROP TRIGGER trg_t09_immutable ON ahdah.project_settlement_events;
DROP TRIGGER trg_t10_immutable ON ahdah.project_closure_certificates;
DROP TRIGGER trg_t11_immutable ON ahdah.project_reopenings;
DROP TRIGGER trg_t12_immutable ON ahdah.project_authorization_decisions;
DROP TRIGGER trg_t13_immutable ON ahdah.project_operational_events;
DROP TRIGGER trg_t14_immutable ON ahdah.settlement_policy_versions;
DROP TRIGGER trg_t15_updated_at ON ahdah.company_settlement_policy_bindings;
DROP TRIGGER trg_t15_fixed_keys ON ahdah.company_settlement_policy_bindings;
DROP TRIGGER trg_t16_immutable ON ahdah.document_custody_events;
DROP TRIGGER trg_t17_immutable ON ahdah.document_policy_exceptions;
DROP TRIGGER trg_t18_immutable ON ahdah.verified_evidence_objects;
DROP TRIGGER trg_t19_updated_at ON ahdah.project_owner_reconciliations;
DROP TRIGGER trg_t19_fixed_keys ON ahdah.project_owner_reconciliations;
DROP TRIGGER trg_t20_updated_at ON ahdah.project_owner_reconciliation_positions;
DROP TRIGGER trg_t20_fixed_keys ON ahdah.project_owner_reconciliation_positions;
DROP TRIGGER trg_t21_updated_at ON ahdah.project_owner_retention_items;
DROP TRIGGER trg_t21_fixed_keys ON ahdah.project_owner_retention_items;
DROP TRIGGER trg_t22_immutable ON ahdah.financial_resolution_effects;
DROP TRIGGER trg_t23_updated_at ON ahdah.supplier_credit_intents;
DROP TRIGGER trg_t23_fixed_keys ON ahdah.supplier_credit_intents;
DROP TRIGGER trg_t24_immutable ON ahdah.supplier_credit_intent_applications;
DROP TRIGGER trg_t25_updated_at ON ahdah.legacy_attribution_reviews;
DROP TRIGGER trg_t25_fixed_keys ON ahdah.legacy_attribution_reviews;
DROP TRIGGER trg_t26_updated_at ON ahdah.legacy_attribution_review_projects;
DROP TRIGGER trg_t26_fixed_keys ON ahdah.legacy_attribution_review_projects;
DROP TRIGGER trg_t03_finalized ON ahdah.custody_operations;
DROP TRIGGER trg_t06_finalized ON ahdah.project_settlements;
DROP TRIGGER trg_t19_finalized ON ahdah.project_owner_reconciliations;
DROP TRIGGER trg_t25_finalized ON ahdah.legacy_attribution_reviews;
DROP TRIGGER trg_t04_parent_sealed ON ahdah.custody_movement_entries;
DROP TRIGGER trg_t26_parent_sealed ON ahdah.legacy_attribution_review_projects;
DROP TRIGGER trg_t20_parent_sealed ON ahdah.project_owner_reconciliation_positions;
DROP TRIGGER trg_t21_parent_sealed ON ahdah.project_owner_retention_items;
DROP TRIGGER trg_t19_complete ON ahdah.project_owner_reconciliations;
DROP TRIGGER trg_t08_insert ON ahdah.project_settlement_snapshot_categories;
DROP TRIGGER trg_t07_packet ON ahdah.project_settlement_snapshots;
DROP TRIGGER trg_t08_packet ON ahdah.project_settlement_snapshot_categories;
DROP TRIGGER trg_settlement_t02_conservation ON ahdah.project_custody_positions;
DROP TRIGGER trg_settlement_t05_conservation ON ahdah.custody_reservations;
DROP TRIGGER trg_settlement_balance_conservation ON ahdah.user_advance_balances;
DROP TRIGGER trg_settlement_t01_control ON ahdah.project_financial_controls;
DROP TRIGGER trg_settlement_project_control ON ahdah.projects;
DROP TRIGGER trg_settlement_t06_control ON ahdah.project_settlements;
DROP TRIGGER trg_settlement_t10_control ON ahdah.project_closure_certificates;
DROP TRIGGER trg_settlement_advance_currency ON ahdah.advances;
DROP TRIGGER trg_t06_approval_packet ON ahdah.project_settlements;
ALTER TABLE ahdah.project_financial_controls DROP CONSTRAINT fk_t01_company_id;
ALTER TABLE ahdah.project_financial_controls DROP CONSTRAINT fk_t01_project_id;
ALTER TABLE ahdah.project_financial_controls DROP CONSTRAINT fk_t01_active_settlement_id;
ALTER TABLE ahdah.project_financial_controls DROP CONSTRAINT fk_t01_active_closure_id;
ALTER TABLE ahdah.project_custody_positions DROP CONSTRAINT fk_t02_company_id;
ALTER TABLE ahdah.project_custody_positions DROP CONSTRAINT fk_t02_user_advance_balance_id;
ALTER TABLE ahdah.project_custody_positions DROP CONSTRAINT fk_t02_project_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_company_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_advance_settlement_resolution_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_requested_by_user_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_approved_by_user_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_authorization_decision_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_idempotency_record_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_source_operation_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_money_transfer_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_expense_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_expense_return_id;
ALTER TABLE ahdah.custody_operations DROP CONSTRAINT fk_t03_legacy_attribution_review_id;
ALTER TABLE ahdah.custody_movement_entries DROP CONSTRAINT fk_t04_company_id;
ALTER TABLE ahdah.custody_movement_entries DROP CONSTRAINT fk_t04_custody_operation_id;
ALTER TABLE ahdah.custody_movement_entries DROP CONSTRAINT fk_t04_project_custody_position_id;
ALTER TABLE ahdah.custody_movement_entries DROP CONSTRAINT fk_t04_balance_ledger_entry_id;
ALTER TABLE ahdah.custody_movement_entries DROP CONSTRAINT fk_t04_reverses_entry_id;
ALTER TABLE ahdah.custody_movement_entries DROP CONSTRAINT fk_t04_actor_user_id;
ALTER TABLE ahdah.custody_reservations DROP CONSTRAINT fk_t05_company_id;
ALTER TABLE ahdah.custody_reservations DROP CONSTRAINT fk_t05_custody_operation_id;
ALTER TABLE ahdah.custody_reservations DROP CONSTRAINT fk_t05_project_custody_position_id;
ALTER TABLE ahdah.custody_reservations DROP CONSTRAINT fk_t05_expense_advance_allocation_id;
ALTER TABLE ahdah.custody_reservations DROP CONSTRAINT fk_t05_transfer_advance_allocation_id;
ALTER TABLE ahdah.custody_reservations DROP CONSTRAINT fk_t05_resolved_by_operation_id;
ALTER TABLE ahdah.project_settlements DROP CONSTRAINT fk_t06_company_id;
ALTER TABLE ahdah.project_settlements DROP CONSTRAINT fk_t06_project_id;
ALTER TABLE ahdah.project_settlements DROP CONSTRAINT fk_t06_previous_settlement_id;
ALTER TABLE ahdah.project_settlements DROP CONSTRAINT fk_t06_policy_version_id;
ALTER TABLE ahdah.project_settlements DROP CONSTRAINT fk_t06_prepared_by_user_id;
ALTER TABLE ahdah.project_settlements DROP CONSTRAINT fk_t06_submitted_by_user_id;
ALTER TABLE ahdah.project_settlements DROP CONSTRAINT fk_t06_approved_by_user_id;
ALTER TABLE ahdah.project_settlements DROP CONSTRAINT fk_t06_snapshot_id;
ALTER TABLE ahdah.project_settlement_snapshots DROP CONSTRAINT fk_t07_company_id;
ALTER TABLE ahdah.project_settlement_snapshots DROP CONSTRAINT fk_t07_project_id;
ALTER TABLE ahdah.project_settlement_snapshots DROP CONSTRAINT fk_t07_project_settlement_id;
ALTER TABLE ahdah.project_settlement_snapshots DROP CONSTRAINT fk_t07_policy_version_id;
ALTER TABLE ahdah.project_settlement_snapshots DROP CONSTRAINT fk_t07_evaluated_by_user_id;
ALTER TABLE ahdah.project_settlement_snapshot_categories DROP CONSTRAINT fk_t08_company_id;
ALTER TABLE ahdah.project_settlement_snapshot_categories DROP CONSTRAINT fk_t08_project_id;
ALTER TABLE ahdah.project_settlement_snapshot_categories DROP CONSTRAINT fk_t08_snapshot_id;
ALTER TABLE ahdah.project_settlement_events DROP CONSTRAINT fk_t09_company_id;
ALTER TABLE ahdah.project_settlement_events DROP CONSTRAINT fk_t09_project_id;
ALTER TABLE ahdah.project_settlement_events DROP CONSTRAINT fk_t09_settlement_id;
ALTER TABLE ahdah.project_settlement_events DROP CONSTRAINT fk_t09_actor_user_id;
ALTER TABLE ahdah.project_settlement_events DROP CONSTRAINT fk_t09_authorization_decision_id;
ALTER TABLE ahdah.project_settlement_events DROP CONSTRAINT fk_t09_snapshot_id;
ALTER TABLE ahdah.project_settlement_events DROP CONSTRAINT fk_t09_idempotency_record_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_company_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_project_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_project_settlement_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_approved_snapshot_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_closure_snapshot_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_policy_version_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_closed_by_user_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_authorization_decision_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_idempotency_record_id;
ALTER TABLE ahdah.project_reopenings DROP CONSTRAINT fk_t11_company_id;
ALTER TABLE ahdah.project_reopenings DROP CONSTRAINT fk_t11_project_id;
ALTER TABLE ahdah.project_reopenings DROP CONSTRAINT fk_t11_previous_closure_id;
ALTER TABLE ahdah.project_reopenings DROP CONSTRAINT fk_t11_new_settlement_id;
ALTER TABLE ahdah.project_reopenings DROP CONSTRAINT fk_t11_actor_user_id;
ALTER TABLE ahdah.project_reopenings DROP CONSTRAINT fk_t11_authorization_decision_id;
ALTER TABLE ahdah.project_reopenings DROP CONSTRAINT fk_t11_audit_log_id;
ALTER TABLE ahdah.project_reopenings DROP CONSTRAINT fk_t11_idempotency_record_id;
ALTER TABLE ahdah.project_authorization_decisions DROP CONSTRAINT fk_t12_company_id;
ALTER TABLE ahdah.project_authorization_decisions DROP CONSTRAINT fk_t12_project_id;
ALTER TABLE ahdah.project_authorization_decisions DROP CONSTRAINT fk_t12_actor_user_id;
ALTER TABLE ahdah.project_authorization_decisions DROP CONSTRAINT fk_t12_policy_version_id;
ALTER TABLE ahdah.project_authorization_decisions DROP CONSTRAINT fk_t12_preparer_user_id;
ALTER TABLE ahdah.project_authorization_decisions DROP CONSTRAINT fk_t12_submitter_user_id;
ALTER TABLE ahdah.project_authorization_decisions DROP CONSTRAINT fk_t12_beneficiary_user_id;
ALTER TABLE ahdah.project_authorization_decisions DROP CONSTRAINT fk_t12_evidence_id;
ALTER TABLE ahdah.project_operational_events DROP CONSTRAINT fk_t13_company_id;
ALTER TABLE ahdah.project_operational_events DROP CONSTRAINT fk_t13_project_id;
ALTER TABLE ahdah.project_operational_events DROP CONSTRAINT fk_t13_actor_user_id;
ALTER TABLE ahdah.project_operational_events DROP CONSTRAINT fk_t13_evidence_id;
ALTER TABLE ahdah.project_operational_events DROP CONSTRAINT fk_t13_acknowledgment_event_id;
ALTER TABLE ahdah.project_operational_events DROP CONSTRAINT fk_t13_authorization_decision_id;
ALTER TABLE ahdah.project_operational_events DROP CONSTRAINT fk_t13_idempotency_record_id;
ALTER TABLE ahdah.settlement_policy_versions DROP CONSTRAINT fk_t14_company_id;
ALTER TABLE ahdah.settlement_policy_versions DROP CONSTRAINT fk_t14_approved_by_user_id;
ALTER TABLE ahdah.settlement_policy_versions DROP CONSTRAINT fk_t14_predecessor_id;
ALTER TABLE ahdah.company_settlement_policy_bindings DROP CONSTRAINT fk_t15_company_id;
ALTER TABLE ahdah.company_settlement_policy_bindings DROP CONSTRAINT fk_t15_active_policy_version_id;
ALTER TABLE ahdah.company_settlement_policy_bindings DROP CONSTRAINT fk_t15_activated_by_user_id;
ALTER TABLE ahdah.document_custody_events DROP CONSTRAINT fk_t16_company_id;
ALTER TABLE ahdah.document_custody_events DROP CONSTRAINT fk_t16_project_id;
ALTER TABLE ahdah.document_custody_events DROP CONSTRAINT fk_t16_evidence_id;
ALTER TABLE ahdah.document_custody_events DROP CONSTRAINT fk_t16_expense_document_id;
ALTER TABLE ahdah.document_custody_events DROP CONSTRAINT fk_t16_actor_user_id;
ALTER TABLE ahdah.document_custody_events DROP CONSTRAINT fk_t16_policy_version_id;
ALTER TABLE ahdah.document_custody_events DROP CONSTRAINT fk_t16_previous_event_id;
ALTER TABLE ahdah.document_custody_events DROP CONSTRAINT fk_t16_authorization_decision_id;
ALTER TABLE ahdah.document_policy_exceptions DROP CONSTRAINT fk_t17_company_id;
ALTER TABLE ahdah.document_policy_exceptions DROP CONSTRAINT fk_t17_project_id;
ALTER TABLE ahdah.document_policy_exceptions DROP CONSTRAINT fk_t17_evidence_id;
ALTER TABLE ahdah.document_policy_exceptions DROP CONSTRAINT fk_t17_expense_document_id;
ALTER TABLE ahdah.document_policy_exceptions DROP CONSTRAINT fk_t17_policy_version_id;
ALTER TABLE ahdah.document_policy_exceptions DROP CONSTRAINT fk_t17_approved_by_user_id;
ALTER TABLE ahdah.document_policy_exceptions DROP CONSTRAINT fk_t17_authorization_decision_id;
ALTER TABLE ahdah.document_policy_exceptions DROP CONSTRAINT fk_t17_supersedes_exception_id;
ALTER TABLE ahdah.verified_evidence_objects DROP CONSTRAINT fk_t18_company_id;
ALTER TABLE ahdah.verified_evidence_objects DROP CONSTRAINT fk_t18_project_id;
ALTER TABLE ahdah.verified_evidence_objects DROP CONSTRAINT fk_t18_expense_document_id;
ALTER TABLE ahdah.verified_evidence_objects DROP CONSTRAINT fk_t18_verified_by_user_id;
ALTER TABLE ahdah.verified_evidence_objects DROP CONSTRAINT fk_t18_source_evidence_id;
ALTER TABLE ahdah.project_owner_reconciliations DROP CONSTRAINT fk_t19_company_id;
ALTER TABLE ahdah.project_owner_reconciliations DROP CONSTRAINT fk_t19_project_id;
ALTER TABLE ahdah.project_owner_reconciliations DROP CONSTRAINT fk_t19_policy_version_id;
ALTER TABLE ahdah.project_owner_reconciliations DROP CONSTRAINT fk_t19_prepared_by_user_id;
ALTER TABLE ahdah.project_owner_reconciliations DROP CONSTRAINT fk_t19_approved_by_user_id;
ALTER TABLE ahdah.project_owner_reconciliations DROP CONSTRAINT fk_t19_evidence_id;
ALTER TABLE ahdah.project_owner_reconciliations DROP CONSTRAINT fk_t19_supersedes_id;
ALTER TABLE ahdah.project_owner_reconciliation_positions DROP CONSTRAINT fk_t20_company_id;
ALTER TABLE ahdah.project_owner_reconciliation_positions DROP CONSTRAINT fk_t20_project_id;
ALTER TABLE ahdah.project_owner_reconciliation_positions DROP CONSTRAINT fk_t20_owner_reconciliation_id;
ALTER TABLE ahdah.project_owner_retention_items DROP CONSTRAINT fk_t21_company_id;
ALTER TABLE ahdah.project_owner_retention_items DROP CONSTRAINT fk_t21_project_id;
ALTER TABLE ahdah.project_owner_retention_items DROP CONSTRAINT fk_t21_owner_position_id;
ALTER TABLE ahdah.project_owner_retention_items DROP CONSTRAINT fk_t21_evidence_id;
ALTER TABLE ahdah.project_owner_retention_items DROP CONSTRAINT fk_t21_approved_by_user_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_company_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_project_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_expense_return_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_advance_settlement_resolution_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_custody_movement_entry_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_funding_source_ledger_entry_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_personal_claim_adjustment_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_personal_claim_write_off_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_supplier_debt_write_off_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_supplier_credit_note_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_supplier_refund_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_authorization_decision_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_evidence_id;
ALTER TABLE ahdah.financial_resolution_effects DROP CONSTRAINT fk_t22_reverses_effect_id;
ALTER TABLE ahdah.supplier_credit_intents DROP CONSTRAINT fk_t23_company_id;
ALTER TABLE ahdah.supplier_credit_intents DROP CONSTRAINT fk_t23_supplier_credit_note_id;
ALTER TABLE ahdah.supplier_credit_intents DROP CONSTRAINT fk_t23_project_id;
ALTER TABLE ahdah.supplier_credit_intents DROP CONSTRAINT fk_t23_prepared_by_user_id;
ALTER TABLE ahdah.supplier_credit_intents DROP CONSTRAINT fk_t23_approved_by_user_id;
ALTER TABLE ahdah.supplier_credit_intent_applications DROP CONSTRAINT fk_t24_company_id;
ALTER TABLE ahdah.supplier_credit_intent_applications DROP CONSTRAINT fk_t24_supplier_credit_intent_id;
ALTER TABLE ahdah.supplier_credit_intent_applications DROP CONSTRAINT fk_t24_supplier_credit_note_allocation_id;
ALTER TABLE ahdah.supplier_credit_intent_applications DROP CONSTRAINT fk_t24_applied_by_user_id;
ALTER TABLE ahdah.supplier_credit_intent_applications DROP CONSTRAINT fk_t24_reverses_application_id;
ALTER TABLE ahdah.legacy_attribution_reviews DROP CONSTRAINT fk_t25_company_id;
ALTER TABLE ahdah.legacy_attribution_reviews DROP CONSTRAINT fk_t25_declared_by_user_id;
ALTER TABLE ahdah.legacy_attribution_reviews DROP CONSTRAINT fk_t25_reviewed_by_user_id;
ALTER TABLE ahdah.legacy_attribution_reviews DROP CONSTRAINT fk_t25_approved_by_user_id;
ALTER TABLE ahdah.legacy_attribution_reviews DROP CONSTRAINT fk_t25_evidence_id;
ALTER TABLE ahdah.legacy_attribution_reviews DROP CONSTRAINT fk_t25_supersedes_review_id;
ALTER TABLE ahdah.legacy_attribution_review_projects DROP CONSTRAINT fk_t26_company_id;
ALTER TABLE ahdah.legacy_attribution_review_projects DROP CONSTRAINT fk_t26_legacy_attribution_review_id;
ALTER TABLE ahdah.legacy_attribution_review_projects DROP CONSTRAINT fk_t26_project_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_cycle_approved_snapshot_id;
ALTER TABLE ahdah.project_closure_certificates DROP CONSTRAINT fk_t10_cycle_closure_snapshot_id;
ALTER TABLE ahdah.projects DROP CONSTRAINT ck_settlement_project_currency, DROP COLUMN contract_currency_code;
ALTER TABLE ahdah.project_contract_changes DROP CONSTRAINT ck_settlement_change_currency, DROP COLUMN currency_code;
ALTER TABLE ahdah.owner_payment_refunds DROP CONSTRAINT ck_settlement_refund_currency, DROP COLUMN currency_code;
DROP TABLE ahdah.legacy_attribution_review_projects;
DROP TABLE ahdah.legacy_attribution_reviews;
DROP TABLE ahdah.supplier_credit_intent_applications;
DROP TABLE ahdah.supplier_credit_intents;
DROP TABLE ahdah.financial_resolution_effects;
DROP TABLE ahdah.project_owner_retention_items;
DROP TABLE ahdah.project_owner_reconciliation_positions;
DROP TABLE ahdah.project_owner_reconciliations;
DROP TABLE ahdah.verified_evidence_objects;
DROP TABLE ahdah.document_policy_exceptions;
DROP TABLE ahdah.document_custody_events;
DROP TABLE ahdah.company_settlement_policy_bindings;
DROP TABLE ahdah.settlement_policy_versions;
DROP TABLE ahdah.project_operational_events;
DROP TABLE ahdah.project_authorization_decisions;
DROP TABLE ahdah.project_reopenings;
DROP TABLE ahdah.project_closure_certificates;
DROP TABLE ahdah.project_settlement_events;
DROP TABLE ahdah.project_settlement_snapshot_categories;
DROP TABLE ahdah.project_settlement_snapshots;
DROP TABLE ahdah.project_settlements;
DROP TABLE ahdah.custody_reservations;
DROP TABLE ahdah.custody_movement_entries;
DROP TABLE ahdah.custody_operations;
DROP TABLE ahdah.project_custody_positions;
DROP TABLE ahdah.project_financial_controls;
DROP FUNCTION ahdah.settlement_advance_currency();
DROP FUNCTION ahdah.settlement_approval_packet();
DROP FUNCTION ahdah.settlement_category_insert();
DROP FUNCTION ahdah.settlement_check_custody();
DROP FUNCTION ahdah.settlement_child_freeze();
DROP FUNCTION ahdah.settlement_control_check();
DROP FUNCTION ahdah.settlement_fixed_keys();
DROP FUNCTION ahdah.settlement_freeze_status();
DROP FUNCTION ahdah.settlement_owner_approval();
DROP FUNCTION ahdah.settlement_packet_check();
DROP FUNCTION ahdah.settlement_custody_authority();
COMMIT;
-- No CASCADE; an unexpected dependency aborts the whole rollback.
-- Dropped tables remove their own new keys/indexes/grants. Baseline functions,
-- roles, sequences, ledgers, indexes and privileges remain unchanged.
